### PR TITLE
Rewrite win-clipboard in Rust

### PR DESCRIPTION
**Pull request by floatdrop**
- It now uses [clipboard_win](https://crates.io/crates/clipboard-win) crate, which proven to be well written and used in Mozilla Servo.
- Windows x64 and x32 binaries are built (https://github.com/sindresorhus/clipboardy/issues/30)
- 🦄 Auto release on tags! (but may require to fix token – [see instructions](https://github.com/japaric/trust/blob/master/appveyor.yml#L62))

@sindresorhus check this out.

### CODE REVIEW

**Comment by floatdrop** [comment]
Binary sizes is kind of a bummer thou – gone from 17Kb to 113Kb.

**Comment by Qix-** [comment]
This is neat and all, and I know this question is going to be met with some resistance -- but I have a burning question:

**Why?**

**Comment by floatdrop** [comment]
@Qix- it could fix broken line endings.

**Comment by sindresorhus** [comment]
> it could fix broken line endings.

Does it fix the broken line endings? Or is this hypothetical?

**Comment by sindresorhus** [comment]
I'm all for this change! 🙌 The previous codebase was unmaintainable, as neither @floatdrop nor I know C very well. Now we can reuse a production-ready dependency and have Rust too, which gives some safety guarantees.

**Comment by sindresorhus** [comment]
@floatdrop I think it's a good idea to merge it into one binary. Tests are currently failing though.

**Comment by floatdrop** [comment]
> Does it fix the broken line endings? Or is this hypothetical?

For now it is hypothetical – . This should be tested within node.

> Tests are currently failing though.

Will fix them soon 🙌

**Comment by floatdrop** [comment]
@sindresorhus ready to merge.

**Comment by sindresorhus** [comment]
Nice work @floatdrop. Looks great 🙌

**Comment by sindresorhus** [comment]
@floatdrop Can you do a new release? And document in the readme how to do a new release?

**Comment by floatdrop** [comment]
@sindresorhus you just need to push a tag and appveyor will create release and attach files automatically.

**Comment by floatdrop** [comment]
@sindresorhus actually you need to replace [token](https://github.com/sindresorhus/win-clipboard/blob/master/appveyor.yml#L35) in config (instructions [here](https://github.com/japaric/trust/blob/master/appveyor.yml#L62)) and then push a tag.

**Comment by sindresorhus** [comment]
Ok. Done, and I pushed a new tag. Let's see if it works.

**Comment by floatdrop** [comment]
```
Error creating GitHub release: Not Found
```

@sindresorhus that's strange. It worked in my fork.

**Pull request merged**
