### PR TITLE
Win32 binaries

### PR DESCRIPTION
**Pull request by floatdrop**
Building binaries for https://github.com/sindresorhus/clipboardy/issues/30

Build is failing now – If someone wants to continue working this, welcome 🦄

### CODE REVIEW

**Comment by Qix-** [comment]
Hey @floatdrop - could you explain what all you're changing here? Been a minute since I've built something on windows.

Thanks :)

**Comment by floatdrop** [comment]
@Qix- I'm trying to build Win32 binaries. One build is hanged, because of wrong path to executables. It will terminated by timeout soon.

**Comment by floatdrop** [comment]
b7e

**Comment by Qix-** [comment]
This is why I hate windows dev haha. I'll let @sindresorhus review.

**Comment by floatdrop** [comment]
@Qix- this is still wip unfortunately.

**Comment by sindresorhus** [comment]
I don't think we should build 32-bit binaries. People should just use 64-bit. Clipboardy gets 123,945 downloads a month, and we've gotten only one single complaint about it being missing.

@floatdrop You're free to add it if you feel strongly about it, but I'm not going to review this.

**Comment by Qix-** [comment]
Oh, that's what this PR is for.

FWIW "win32" just refers to windows, not windows 32-bit. :) :+1: to what @sindresorhus said.

**Comment by xconverge** [comment]
Just noting we got a request for this over at VSCodeVim 

https://github.com/VSCodeVim/Vim/issues/2074

So I wouldn't say it is a wasted effort if it cuts down on some noise/debugging/troubleshooting for all.

I just happened to check this repo last week to see this PR so I knew what was going on with our user without much wasted time...

Thanks for the package! It has been great!

**Comment by floatdrop** [comment]
Let's try different approach.

**Pull request closed without merging**
