### PR TITLE
Use proper line ending

### PR DESCRIPTION
**Pull request by floatdrop**
From @DavidAnson comment: https://github.com/sindresorhus/clipboardy/issues/25#issuecomment-309353051

### CODE REVIEW

**Comment by floatdrop** [comment]
@DavidAnson thanks for pointing that out. Test is kind-a there – https://github.com/sindresorhus/win-clipboard/blob/master/test.bat#L46-L56 (may be it should be splitted into multiple checks to reproduce this bug).

**Comment by DavidAnson** [comment]
Agree, it would be nice to see the tests fail without this change. :)

**Comment by DavidAnson** [comment]
Can you please double-check that GMEM_ZEROINIT made it into the final commit? We need that to ensure the last bytes are 0.

**Comment by floatdrop** [comment]
@DavidAnson yep, missed that.

**Pull request merged**
